default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_dev
  password: postgres
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biblioteca_de_filmes_development

test:
  <<: *default
  database: biblioteca_de_filmes_test
